sonar.projectKey=Hwi-SRE_nodejs-demo-docker
sonar.organization=codearts-agent-demo
sonar.projectName=AoE2 Unit Browser
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/testing/**
sonar.typescript.lcov.reportPaths=coverage/lcov/lcov.info
sonar.scm.provider=git
