name: Manual Trigger Demo

on:
  workflow_dispatch:
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Show trigger message
        run: echo "✅ Deployment successfully finished!-v2"
